version: '3.8'
services:
 db:
  image: postgres
  # Caso queira manter os em um volume
  # volumes:
  #  - ./_data/db:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
  
  healthcheck:
    test: ["CMD", "pg_isready"]
    interval: 10s
    timeout: 1s
    retries: 3
    start_period: 2s

 app:
  image: kombi
  environment:
    - host=db
    # - DB_PORT=5432
    # - DB_USER=postgres
    # - DB_PASSWORD=postgres
    # - DB_NAME=postgres
  ports:
  - "8080:8080"
  depends_on:
    db:
      condition: service_healthy