version: '3.8'
services:
 db:
  image: postgres
  # Caso queira manter os em um volume
  # volumes:
  #  - ./_data/db:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres